# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-service
#   namespace: taneka
# spec:
#   # Service configuration for Minikube
#   type: NodePort
#   selector:
#     app: twoge # This is the label that the service will use to select the pods it will route traffic to
#   ports:
#     - protocol: TCP
#       port: 80       # Port exposed by the service
#       targetPort: 80  # Port on the pod that the service should forward to
#       # nodePort: 30009   # Port on which the service will be exposed on the Minikube node

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: taneka
spec:
  # Service configuration for EKS
  type: LoadBalancer # This will expose the service to the internet
  selector:
    app: twoge # This is the label that the service will use to select the pods it will route traffic to
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 80  # Port on the pod that the service should forward to
      nodePort: 30009