---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: taneka
spec:
  storageClassName: taneka-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce